import { COLORS } from "./variables";
import General from "../definitions/General";

const GENERAL: General = {
   BACKGROUND_IMAGE: "none",
   FOOTER_LINKS_COLOR: { DEFAULT: COLORS.GREY, HOVER: COLORS.GREEN },
   SITE_BACKGROUND_COLOR: "#fff",
   NAV_ITEMS_COLOR: { DEFAULT: COLORS.GREY, HOVER: COLORS.GREEN },
   HEADER_COLOR: COLORS.LIGHT_GREEN,
   LOGO_COLOR: { DEFAULT: COLORS.GREY, HOVER: COLORS.GREEN }
};

export default GENERAL;
