import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/libs/utils";
import { TailwindIndicator } from "@/components/TailwindIndicator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <div className="mx-auto container max-w-screen-xl px-4 flex flex-col md:flex-row md:px-12">
          <Header />
          {children}
        </div>
        <TailwindIndicator />
      </body>
    </html>
  );
}
